name: picturo_app
description: "A English Learning app."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  lottie: ^2.0.0 # Add the latest version of the lottie package

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  carousel_slider: ^4.2.1
  animated_toggle_switch: ^0.8.4
  location: ^8.0.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0 
  flutter_svg: ^2.1.0
  shimmer: ^3.0.0
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  http: ^1.3.0
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.3
  provider: ^6.1.2
  fluttertoast: ^8.2.12
  flutter_launcher_icons: ^0.14.3
  razorpay_flutter: ^1.4.0
  socket_io_client: ^3.0.2
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.2.1
  speech_to_text: ^7.0.0
  permission_handler: ^12.0.0
  flutter_tts: ^4.2.3
  cached_network_image: ^3.4.1
  go_router: ^15.1.1
  audioplayers: ^6.4.0
  path_provider: ^2.1.5
  just_audio: ^0.10.1
  firebase_analytics: ^11.4.5
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  cloud_firestore: ^5.6.7
  googleapis_auth: ^2.0.0
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.1
  flutter_vector_icons: ^2.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  flutter_callkit_incoming: ^2.5.2
  audio_session: ^0.2.2
  animations: ^2.0.11
  share_plus: ^11.0.0
  phone_state: ^2.1.1
  in_app_review: ^2.0.10
  flutter_webrtc: ^0.14.2
  vibration: ^3.1.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png" 
  adaptive_icon_background: "#241065" 
  adaptive_icon_foreground: "assets/app_icon.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/login_illustration.png
     - assets/solar_lock-linear.png
     - assets/Vector.png
     - assets/Illustration.png
     - assets/iconamoon_profile-thin.png
     - assets/lottie/Lottie Successful.json
     - assets/gender_age.png
     - assets/location page.png
     - assets/chat_filled.png
     - assets/chat_unfilled.png
     - assets/game_unfilled.png
     - assets/game_filled.png
     - assets/house_filled.png
     - assets/house_unfilled.png
     - assets/notification_filled.png
     - assets/notification_unfilled.png
     - assets/idioms.png
     - assets/phrasal verb.png
     - assets/adverb.png
     - assets/adjective.png
     - assets/work and success.png
     - assets/money and finance.png
     - assets/emotions and feelings.png
     - assets/time and punctuality.png
     - assets/verbs.png
     - assets/profile_default.png
     - assets/select_language.png
     - assets/avatar_1.png
     - assets/avatar_2.png
     - assets/avatar_3.png
     - assets/avatar_4.png
     - assets/avatar_10.png
     - assets/avatar_5.png
     - assets/avatar_6.png
     - assets/avatar_7.png
     - assets/avatar_8.png
     - assets/avatar_9.png
     - assets/panda.png
     - assets/subs.png
     - assets/idiom_1.png
     - assets/star.png
     - assets/picturo_logo.png
     - assets/game1.png
     - assets/game2.png
     - assets/game3.png
     - assets/write.png
     - assets/jump.png
     - assets/run.png
     - assets/walk.png
     - assets/eat.png
     - assets/waiting.png
     - assets/sleep.png
     - assets/fluent_bot-28-filled.png
     - assets/Emoji.png
     - assets/Picturo English.png
     - assets/certificates/certificate.crt 
     - assets/certificates/certificate.der 
     - assets/certificates/combined.pem
     - assets/certificates/certificate.pem
     - assets/certificates/private.key
     - assets/avatar2.png
     - assets/run.gif
     - assets/ai_avatar.png
     - assets/app_icon.png
     - assets/support.png
     - assets/svgs/study.svg
     - assets/svgs/game_intro.svg
     - assets/chat_intro.jpg
     - assets/convo_intro.jpg
     - assets/audio/bg_music.mp3
     - assets/audio/drop.mp3
     - assets/audio/drag.mp3
     - assets/audio/quest_gm_bg.mp3

     

     

  fonts:
    - family: Poppins Black
      fonts:
        - asset: fonts/Poppins-Black.ttf

    - family: Poppins Medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf

    - family: Poppins Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
   
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
